import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ur';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
  isUrdu: boolean;
}

const translations: Record<string, Record<Language, string>> = {
  // Common
  english: { en: 'English', ur: 'انگریزی' },
  urdu: { en: 'اردو', ur: 'اردو' },

  // Login
  welcomeBack: { en: 'Welcome Back', ur: 'خوش آمدید' },
  signInToAccount: { en: 'Sign in to your account', ur: 'اپنے اکاؤنٹ میں داخل ہوں' },
  emailPhoneCnic: { en: 'Email, Phone No, or CNIC Number', ur: 'ای میل، فون نمبر، یا شناختی کارڈ نمبر' },
  enterEmailPhoneCnic: { en: 'Enter email', ur: 'ای میل درج کریں' },
  password: { en: 'Password', ur: 'پاس ورڈ' },
  enterPassword: { en: 'Enter your password', ur: 'اپنا پاس ورڈ درج کریں' },
  signIn: { en: 'Sign In →', ur: '← داخل ہوں' },
  dontHaveAccount: { en: "Don't have an account? ", ur: 'اکاؤنٹ نہیں ہے؟ ' },
  createAccount: { en: 'Create Account', ur: 'اکاؤنٹ بنائیں' },
  farmNestCopyright: { en: 'Farm Nest © 2025', ur: 'فارم نیسٹ © 2025' },
  fieldRequired: { en: 'This field is required.', ur: 'یہ خانہ ضروری ہے۔' },
  passwordRequired: { en: 'Password is required.', ur: 'پاس ورڈ ضروری ہے۔' },
  noAccountFound: { en: 'No account found with this information.', ur: 'اس معلومات سے کوئی اکاؤنٹ نہیں ملا۔' },
  incorrectPassword: { en: 'Incorrect password.', ur: 'غلط پاس ورڈ۔' },
  accountSuspended: { en: 'Your account has been suspended.', ur: 'آپ کا اکاؤنٹ معطل کر دیا گیا ہے۔' },
  accountRejected: { en: 'Your account has been rejected. Please contact support.', ur: 'آپ کا اکاؤنٹ مسترد کر دیا گیا ہے۔ براہ کرم سپورٹ سے رابطہ کریں۔' },
  adminAccountRejected: { en: 'Your admin account has been rejected. Please contact the Main Admin.', ur: 'آپ کا ایڈمن اکاؤنٹ مسترد کر دیا گیا ہے۔ براہ کرم مرکزی ایڈمن سے رابطہ کریں۔' },
  identifierRequired: { en: 'Email, Phone or CNIC is required.', ur: 'ای میل، فون یا شناختی کارڈ نمبر ضروری ہے۔' },

  // Forgot Password
  forgotPassword: { en: 'Forgot Password?', ur: 'پاس ورڈ بھول گئے؟' },
  fpTitle: { en: 'Reset Password', ur: 'پاس ورڈ ری سیٹ کریں' },
  fpSubtitle: { en: 'Enter your email to receive a verification code.', ur: 'تصدیقی کوڈ حاصل کرنے کے لیے اپنا ای میل درج کریں۔' },

  // Step 1 — Email
  fpStep1Label: { en: 'Step 1 — Enter Your Email', ur: 'مرحلہ 1 — اپنا ای میل درج کریں' },
  fpStep1Desc: { en: 'We will send a 10-character verification code to your registered email address.', ur: 'ہم آپ کے رجسٹرڈ ای میل پر 10 حروف کا تصدیقی کوڈ بھیجیں گے۔' },
  fpEmailLabel: { en: 'Email Address', ur: 'ای میل پتہ' },
  fpEmailPlaceholder: { en: 'Enter your registered email', ur: 'اپنا رجسٹرڈ ای میل درج کریں' },
  fpEmailRequired: { en: 'Please enter your email address.', ur: 'براہ کرم اپنا ای میل پتہ درج کریں۔' },
  fpEmailInvalid: { en: 'Please enter a valid email address.', ur: 'براہ کرم درست ای میل پتہ درج کریں۔' },
  fpNoAccountFound: { en: 'No account found with this email address.', ur: 'اس ای میل پتے سے کوئی اکاؤنٹ نہیں ملا۔' },
  fpAdminNotAllowed: { en: 'Password reset is not available for this account.', ur: 'اس اکاؤنٹ کے لیے پاس ورڈ ری سیٹ دستیاب نہیں ہے۔' },
  fpSendCodeBtn: { en: 'Send Verification Code →', ur: '← تصدیقی کوڈ بھیجیں' },
  fpSendFailed: { en: 'Failed to send email. Please check your connection and try again.', ur: 'ای میل بھیجنا ناکام ہوا۔ براہ کرم اپنا کنکشن چیک کریں اور دوبارہ کوشش کریں۔' },
  fpBackToLogin: { en: '← Back to Login', ur: '→ لاگ ان پر واپس' },

  // Step 2 — Code verification
  fpStep2Label: { en: 'Step 2 — Enter Verification Code', ur: 'مرحلہ 2 — تصدیقی کوڈ درج کریں' },
  fpStep2Desc: { en: 'A 10-character code has been sent to', ur: '10 حروف کا کوڈ بھیجا گیا ہے' },
  fpCodeLabel: { en: 'Verification Code', ur: 'تصدیقی کوڈ' },
  fpCodePlaceholder: { en: 'Enter 10-character code', ur: '10 حروف کا کوڈ درج کریں' },
  fpCodeRequired: { en: 'Please enter the verification code.', ur: 'براہ کرم تصدیقی کوڈ درج کریں۔' },
  fpCodeInvalid: { en: 'Incorrect code. Please check and try again.', ur: 'غلط کوڈ۔ براہ کرم چیک کریں اور دوبارہ کوشش کریں۔' },
  fpCodeExpired: { en: 'This code has expired. Please request a new one.', ur: 'یہ کوڈ میعاد ختم ہوگئی ہے۔ براہ کرم نیا کوڈ حاصل کریں۔' },
  fpCodeExpiredLabel: { en: 'Code Expired — Request a new one below', ur: 'کوڈ کی میعاد ختم — نیچے سے نیا کوڈ حاصل کریں' },
  fpCodeExpiresIn: { en: 'Code expires in', ur: 'کوڈ میعاد ختم ہوگا' },
  fpVerifyCodeBtn: { en: 'Verify Code →', ur: '← کوڈ تصدیق کریں' },
  fpDidntReceive: { en: "Didn't receive the code? ", ur: 'کوڈ نہیں ملا؟ ' },
  fpResendCode: { en: 'Resend', ur: 'دوبارہ بھیجیں' },
  fpGoBack: { en: '← Go Back', ur: '→ واپس جائیں' },

  // Step 3 — New password
  fpStep3Label: { en: 'Step 3 — Set New Password', ur: 'مرحلہ 3 — نیا پاس ورڈ سیٹ کریں' },
  fpStep3Desc: { en: 'Create a strong new password for your account.', ur: 'اپنے اکاؤنٹ کے لیے ایک مضبوط نیا پاس ورڈ بنائیں۔' },
  fpNewPasswordLabel: { en: 'New Password', ur: 'نیا پاس ورڈ' },
  fpNewPasswordPlaceholder: { en: 'Enter new password', ur: 'نیا پاس ورڈ درج کریں' },
  fpNewPasswordRequired: { en: 'New password is required.', ur: 'نیا پاس ورڈ ضروری ہے۔' },
  fpPasswordMin6: { en: 'Password must be at least 6 characters.', ur: 'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے۔' },
  fpConfirmPasswordLabel: { en: 'Confirm New Password', ur: 'نئے پاس ورڈ کی تصدیق کریں' },
  fpConfirmPasswordPlaceholder: { en: 'Re-enter new password', ur: 'نیا پاس ورڈ دوبارہ درج کریں' },
  fpConfirmPasswordRequired: { en: 'Please confirm your new password.', ur: 'براہ کرم نئے پاس ورڈ کی تصدیق کریں۔' },
  fpPasswordsMismatch: { en: 'Passwords do not match.', ur: 'پاس ورڈ مماثل نہیں ہیں۔' },
  fpResetBtn: { en: '🔐 Reset Password', ur: '🔐 پاس ورڈ ری سیٹ کریں' },

  // Success
  fpSuccessTitle: { en: 'Password Reset Successful!', ur: 'پاس ورڈ کامیابی سے ری سیٹ ہوگیا!' },
  fpSuccessMsg: { en: 'Your password has been updated successfully. You can now log in with your new password.', ur: 'آپ کا پاس ورڈ کامیابی سے اپڈیٹ ہوگیا ہے۔ اب آپ نئے پاس ورڈ سے لاگ ان کر سکتے ہیں۔' },
  fpGoToLogin: { en: '→ Go to Login', ur: '← لاگ ان پر جائیں' },

  // Register
  createAccountTitle: { en: 'Create Account', ur: 'اکاؤنٹ بنائیں' },
  joinCommunity: { en: 'Join the Farm Nest community', ur: 'فارم نیسٹ کمیونٹی میں شامل ہوں' },
  selectRole: { en: 'Select Your Role', ur: 'اپنا کردار منتخب کریں' },
  firstName: { en: 'First Name', ur: 'پہلا نام' },
  enterFirstName: { en: 'Enter your first name', ur: 'اپنا پہلا نام درج کریں' },
  lastName: { en: 'Last Name', ur: 'آخری نام' },
  enterLastName: { en: 'Enter your last name', ur: 'اپنا آخری نام درج کریں' },
  emailAddress: { en: 'Email Address', ur: 'ای میل پتہ' },
  enterEmail: { en: 'Enter your email', ur: 'اپنا ای میل درج کریں' },
  phoneNumber: { en: 'Phone Number', ur: 'فون نمبر' },
  enterPhone: { en: 'Enter your phone number', ur: 'اپنا فون نمبر درج کریں' },
  city: { en: 'City', ur: 'شہر' },
  enterCity: { en: 'Enter your city', ur: 'اپنا شہر درج کریں' },
  completeAddress: { en: 'Complete Address', ur: 'مکمل پتہ' },
  enterAddress: { en: 'Enter your complete address', ur: 'اپنا مکمل پتہ درج کریں' },
  cnicNumber: { en: 'CNIC Number', ur: 'شناختی کارڈ نمبر' },
  enterCnic: { en: 'Enter your CNIC number', ur: 'شناختی کارڈ نمبر درج کریں' },
  cnicFrontImage: { en: 'CNIC Front Side Image', ur: 'شناختی کارڈ اگلی طرف کی تصویر' },
  cnicBackImage: { en: 'CNIC Back Side Image', ur: 'شناختی کارڈ پچھلی طرف کی تصویر' },
  uploadFrontCnic: { en: 'Upload Front Side of CNIC', ur: 'شناختی کارڈ کی اگلی سائیڈ اپلوڈ کریں' },
  uploadBackCnic: { en: 'Upload Back Side of CNIC', ur: 'شناختی کارڈ کی پچھلی سائیڈ اپلوڈ کریں' },
  tapSelectGallery: { en: 'Tap to select from gallery', ur: 'گیلری سے منتخب کرنے کے لیے ٹیپ کریں' },
  frontImageSelected: { en: '✔ Front Image Selected', ur: '✔ اگلی تصویر منتخب ہوئی' },
  backImageSelected: { en: '✔ Back Image Selected', ur: '✔ پچھلی تصویر منتخب ہوئی' },
  tapToChange: { en: 'Tap to change', ur: 'تبدیل کرنے کے لیے ٹیپ کریں' },
  confirmPassword: { en: 'Confirm Password', ur: 'پاس ورڈ کی تصدیق کریں' },
  reEnterPassword: { en: 'Re-enter your password', ur: 'اپنا پاس ورڈ دوبارہ درج کریں' },
  createAccountBtn: { en: 'Create Account →', ur: '← اکاؤنٹ بنائیں' },
  alreadyHaveAccount: { en: 'Already have an account? ', ur: 'پہلے سے اکاؤنٹ ہے؟ ' },
  signInLink: { en: 'Sign In', ur: 'داخل ہوں' },
  firstNameRequired: { en: 'First Name is required.', ur: 'پہلا نام ضروری ہے۔' },
  lastNameRequired: { en: 'Last Name is required.', ur: 'آخری نام ضروری ہے۔' },
  emailRequired: { en: 'Email is required.', ur: 'ای میل ضروری ہے۔' },
  validEmail: { en: 'Please enter a valid email.', ur: 'براہ کرم درست ای میل درج کریں۔' },
  phoneRequired: { en: 'Phone Number is required.', ur: 'فون نمبر ضروری ہے۔' },
  phoneNumbersOnly: { en: 'Phone Number must contain only numbers.', ur: 'فون نمبر میں صرف اعداد ہونے چاہئیں۔' },
  cityRequired: { en: 'City is required.', ur: 'شہر ضروری ہے۔' },
  addressRequired: { en: 'Address is required.', ur: 'پتہ ضروری ہے۔' },
  cnicRequired: { en: 'CNIC Number is required.', ur: 'شناختی کارڈ نمبر ضروری ہے۔' },
  cnicNumbersOnly: { en: 'CNIC Number must contain only numbers.', ur: 'شناختی کارڈ نمبر میں صرف اعداد ہونے چاہئیں۔' },
  cnicMustNumbers: { en: 'CNIC must contain only numbers.', ur: 'شناختی کارڈ میں صرف اعداد ہونے چاہئیں۔' },
  phoneMust11Digits: { en: 'Phone Number must be exactly 11 digits.', ur: 'فون نمبر بالکل 11 ہندسوں کا ہونا چاہیے۔' },
  cnicMust13Digits: { en: 'CNIC Number must be exactly 13 digits.', ur: 'شناختی کارڈ نمبر بالکل 13 ہندسوں کا ہونا چاہیے۔' },
  cnicFrontRequired: { en: 'Front side CNIC image is required.', ur: 'شناختی کارڈ کی اگلی طرف کی تصویر ضروری ہے۔' },
  cnicBackRequired: { en: 'Back side CNIC image is required.', ur: 'شناختی کارڈ کی پچھلی طرف کی تصویر ضروری ہے۔' },
  passwordRequired2: { en: 'Password is required.', ur: 'پاس ورڈ ضروری ہے۔' },
  passwordMinLength: { en: 'Password must be at least 6 characters.', ur: 'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے۔' },
  confirmPasswordRequired: { en: 'Please confirm your password.', ur: 'براہ کرم پاس ورڈ کی تصدیق کریں۔' },
  passwordsDontMatch: { en: 'Passwords do not match.', ur: 'پاس ورڈ مماثل نہیں ہیں۔' },
  emailAlreadyRegistered: { en: 'This email is already registered.', ur: 'یہ ای میل پہلے سے رجسٹرڈ ہے۔' },
  selfiePhoto: { en: 'Selfie Photo', ur: 'سیلفی تصویر' },
  uploadSelfie: { en: 'Upload Your Selfie', ur: 'اپنی سیلفی اپلوڈ کریں' },
  selfieSelected: { en: '✔ Selfie Selected', ur: '✔ سیلفی منتخب ہوئی' },
  selfieRequired: { en: 'Selfie photo is required.', ur: 'سیلفی تصویر ضروری ہے۔' },

  // Profile
  profile: { en: 'Profile', ur: 'پروفائل' },
  personalInformation: { en: 'Personal Information', ur: 'ذاتی معلومات' },
  accountNumber: { en: 'Account Number', ur: 'اکاؤنٹ نمبر' },
  email: { en: 'Email', ur: 'ای میل' },
  phone: { en: 'Phone Number', ur: 'فون نمبر' },
  cityLabel: { en: 'City', ur: 'شہر' },
  address: { en: 'Address', ur: 'پتہ' },
  edit: { en: '✏️ Edit', ur: '✏️ ترمیم' },
  newPassword: { en: 'New Password (leave empty to keep current)', ur: 'نیا پاس ورڈ (موجودہ رکھنے کے لیے خالی چھوڑیں)' },
  enterNewPassword: { en: 'Enter new password...', ur: 'نیا پاس ورڈ درج کریں...' },
  updateProfile: { en: '💾 Update Profile', ur: '💾 پروفائل اپڈیٹ کریں' },
  cancel: { en: 'Cancel', ur: 'منسوخ کریں' },
  logout: { en: '🚪 Logout', ur: '🚪 لاگ آؤٹ' },
  reviewsReceived: { en: '⭐ Reviews Received', ur: '⭐ موصول شدہ جائزے' },
  reviews: { en: 'reviews', ur: 'جائزے' },
  updateSuccess: { en: 'Your information update successfully', ur: 'آپ کی معلومات کامیابی سے اپڈیٹ ہوگئی' },
  errorFillFields: { en: 'Please fill all required fields.', ur: 'براہ کرم تمام ضروری خانے پُر کریں۔' },
  allFieldsRequired: { en: 'All fields are required.', ur: 'تمام خانے ضروری ہیں۔' },
  accountStatus: { en: 'Account:', ur: 'اکاؤنٹ:' },
  farmer: { en: '🌾 Farmer', ur: '🌾 کسان' },
  buyer: { en: '🛒 Buyer', ur: '🛒 خریدار' },
  investor: { en: '💼 Investor', ur: '💼 سرمایہ کار' },
  farmerRole: { en: 'Farmer', ur: 'کسان' },
  buyerRole: { en: 'Buyer', ur: 'خریدار' },
  investorRole: { en: 'Investor', ur: 'سرمایہ کار' },
  adminRole: { en: 'Admin', ur: 'ایڈمن' },
  thanksForRegistration: { en: '🎉 Thanks for registration', ur: '🎉 رجسٹریشن کا شکریہ' },

  // Drawer menus
  menuDashboard: { en: 'Crops Listing', ur: 'فصل کی فہرست' },
  menuMandi:     { en: 'Mandi Prices', ur: 'منڈی قیمتیں' },
  menuFunding: { en: 'Funding', ur: 'فنڈنگ' },
  menuFarmerFunding: { en: 'Farmer Funding', ur: 'کسان فنڈنگ' },
  menuMessages: { en: 'Messages', ur: 'پیغامات' },
  menuItemList: { en: 'Item List', ur: 'اشیاء کی فہرست' },
  menuHistory: { en: 'History', ur: 'تاریخ' },
  menuPayment: { en: 'Payment', ur: 'ادائیگی' },
  menuNotifications: { en: 'Notifications', ur: 'اطلاعات' },
  menuProfile: { en: 'Profile', ur: 'پروفائل' },
  menuComplain: { en: 'Complain', ur: 'شکایت' },
  menuHome: { en: 'Home', ur: 'ہوم' },
  menuMyInvestments: { en: 'My Investments', ur: 'میری سرمایہ کاریاں' },
  menuInvestmentGuideline: { en: 'Investment Guideline', ur: 'سرمایہ کاری رہنما' },
  menuOrders: { en: 'Orders', ur: 'آرڈرز' },
  drawerFarmerRole: { en: '🌾 Farmer', ur: '🌾 کسان' },
  drawerBuyerRole: { en: '🛒 Buyer', ur: '🛒 خریدار' },
  drawerInvestorRole: { en: '💼 Investor', ur: '💼 سرمایہ کار' },

  // ── Inner Screen shared strings ─────────────────────────────────────────────
  noMessagesYet: { en: 'No Messages Yet', ur: 'ابھی کوئی پیغام نہیں' },
  noMessagesSubtitle: { en: 'When buyers or investors message you,\nthey will appear here.', ur: 'جب خریدار یا سرمایہ کار آپ کو پیغام بھیجیں گے،\nوہ یہاں نظر آئیں گے۔' },
  buyerNoMessagesSubtitle: { en: 'When farmers message you,\nthey will appear here.', ur: 'جب کسان آپ کو پیغام بھیجیں گے،\nوہ یہاں نظر آئیں گے۔' },
  investorNoMessagesSubtitle: { en: 'When farmers message you,\nthey will appear here.', ur: 'جب کسان آپ کو پیغام بھیجیں گے،\nوہ یہاں نظر آئیں گے۔' },
  typeMessage: { en: 'Type a message...', ur: 'پیغام لکھیں...' },
  allRead: { en: 'All Read', ur: 'سب پڑھیں' },
  noNotifications: { en: 'No Notifications', ur: 'کوئی اطلاع نہیں' },
  notificationsSubtitle: { en: 'Your activity notifications will appear here.', ur: 'آپ کی سرگرمیوں کی اطلاعات یہاں نظر آئیں گی۔' },
  messages: { en: 'Messages', ur: 'پیغامات' },
  notifications: { en: 'Notifications', ur: 'اطلاعات' },
  sendMsg: { en: 'Send message to', ur: 'پیغام بھیجیں' },

  // Shared Messages screen strings
  noMessages: { en: 'No Messages', ur: 'کوئی پیغام نہیں' },
  tapToMessageFarmer: { en: 'Tap ✏️ to message a farmer.', ur: 'کسان کو پیغام کرنے کے لیے ✏️ دبائیں۔' },
  tapToMessageFarmerLand: { en: 'Tap ✏️ to message a farmer about their land.', ur: 'زمین کے بارے میں کسان کو پیغام کرنے کے لیے ✏️ دبائیں۔' },
  messageAFarmer: { en: 'Message a Farmer', ur: 'کسان کو پیغام کریں' },
  noFarmersWithCrops: { en: 'No farmers with active crops found.', ur: 'فعال فصلوں والا کوئی کسان نہیں ملا۔' },
  noFarmersWithLand: { en: 'No farmers with active land listings found.', ur: 'فعال زمین لسٹنگ والا کوئی کسان نہیں ملا۔' },
  sendSentBy: { en: 'Send You Message', ur: 'نے آپ کو پیغام بھیجا' },

  // Chat box shared strings
  tapToVisitProfile: { en: 'Tap to visit profile', ur: 'پروفائل دیکھنے کے لیے ٹیپ کریں' },
  farmerProfileTitle: { en: 'Farmer Profile', ur: 'کسان کی پروفائل' },
  backArrow: { en: '← Back', ur: '→ واپس' },
  seeAllReviews: { en: 'See All Reviews', ur: 'تمام جائزے دیکھیں' },
  noReviewsYet: { en: 'No reviews yet', ur: 'ابھی کوئی جائزہ نہیں' },
  reviewsCountLabel: { en: 'reviews', ur: 'جائزے' },
  farmerRoleLabel: { en: 'Farmer', ur: 'کسان' },
  infoAccountNumber: { en: 'Account Number', ur: 'اکاؤنٹ نمبر' },
  infoEmail: { en: 'Email', ur: 'ای میل' },
  infoPhone: { en: 'Phone', ur: 'فون' },
  infoCity: { en: 'City', ur: 'شہر' },
  infoAddress: { en: 'Address', ur: 'پتہ' },
  voiceMessagePreview: { en: '🎤 Voice message', ur: '🎤 وائس میسج' },
  imagePreview: { en: '📷 Image', ur: '📷 تصویر' },
  deleteMessageTitle: { en: 'Delete Message', ur: 'پیغام حذف کریں' },
  deleteMessageConfirm: { en: 'Are you sure you want to delete this message?', ur: 'کیا آپ واقعی یہ پیغام حذف کرنا چاہتے ہیں؟' },
  cancelLabel2: { en: 'Cancel', ur: 'منسوخ کریں' },
  deleteLabel2: { en: 'Delete', ur: 'حذف کریں' },
  cancelRecordingBtn: { en: '✕ Cancel', ur: '✕ منسوخ کریں' },

  // Farmer Home (Dashboard)
  dashboard: { en: 'Dashboard', ur: 'ڈیش بورڈ' },
  listYourCrop: { en: 'List Your Crop', ur: 'اپنی فصل لسٹ کریں' },
  postCropsForBuyers: { en: 'Post crops for buyers to bid on', ur: 'خریداروں کے لیے فصلیں پوسٹ کریں' },
  accountPending: { en: 'Account pending. Tap to learn more.', ur: 'اکاؤنٹ زیر التواء ہے۔ مزید جاننے کے لیے ٹیپ کریں۔' },
  cropImages: { en: '📸 Crop Images (Max 3)', ur: '📸 فصل کی تصاویر (زیادہ سے زیادہ 3)' },
  addPhoto: { en: 'Add Photo', ur: 'تصویر شامل کریں' },
  cropTitle: { en: 'Crop Title', ur: 'فصل کا عنوان' },
  enterCropTitle: { en: 'Enter Your Crop Title', ur: 'اپنی فصل کا عنوان درج کریں' },
  cropDescription: { en: 'Crop Description', ur: 'فصل کی تفصیل' },
  enterCropDescription: { en: 'Enter Your Complete detail of Crop', ur: 'فصل کی مکمل تفصیل درج کریں' },
  enterYourCity: { en: 'Enter Your City', ur: 'اپنا شہر درج کریں' },
  enterCompleteAddress: { en: 'Enter your complete Address', ur: 'اپنا مکمل پتہ درج کریں' },
  paymentMethod: { en: 'Payment Method', ur: 'ادائیگی کا طریقہ' },
  accountDetails: { en: 'Account Details', ur: 'اکاؤنٹ کی تفصیلات' },
  accountNumberLabel: { en: 'Account Number', ur: 'اکاؤنٹ نمبر' },
  enterAccountNumber: { en: 'Enter Account Number', ur: 'اکاؤنٹ نمبر درج کریں' },
  accountHolderName: { en: 'Account Holder Name', ur: 'اکاؤنٹ ہولڈر کا نام' },
  enterNameOnAccount: { en: 'Enter Name on Account', ur: 'اکاؤنٹ پر نام درج کریں' },
  bidEndTime: { en: '⏱ Bid End Time', ur: '⏱ بولی ختم ہونے کا وقت' },
  days: { en: 'Days', ur: 'دن' },
  hours: { en: 'Hours', ur: 'گھنٹے' },
  mins: { en: 'Mins', ur: 'منٹ' },
  basePrice: { en: '💰 Base Price (PKR)', ur: '💰 بنیادی قیمت (روپے)' },
  shareLiveLocation: { en: '📍 Share Live Location', ur: '📍 لائیو مقام شیئر کریں' },
  locationCaptured: { en: '✅ Location captured', ur: '✅ مقام محفوظ ہوگیا' },
  buyersWillSeeLocation: { en: 'Buyers will see your exact farm location on Google Maps', ur: 'خریدار گوگل میپ پر آپ کا کھیت دیکھ سکیں گے' },
  submitCropListing: { en: '🚀 Submit Crop Listing', ur: '🚀 فصل کی لسٹنگ جمع کریں' },
  accountPendingBtn: { en: '🔒 Account Pending', ur: '🔒 اکاؤنٹ زیر التواء' },
  yourRecentListings: { en: 'Your Recent Listings', ur: 'آپ کی حالیہ لسٹنگز' },
  pleaseUploadCropImage: { en: 'Please upload at least 1 crop image.', ur: 'براہ کرم کم از کم 1 فصل کی تصویر اپلوڈ کریں۔' },
  cropTitleRequired: { en: 'Crop title is required.', ur: 'فصل کا عنوان ضروری ہے۔' },
  descriptionRequired: { en: 'Description is required.', ur: 'تفصیل ضروری ہے۔' },
  cityRequired2: { en: 'City is required.', ur: 'شہر ضروری ہے۔' },
  addressRequired2: { en: 'Address is required.', ur: 'پتہ ضروری ہے۔' },
  selectPaymentMethod: { en: 'Please select a payment method.', ur: 'براہ کرم ادائیگی کا طریقہ منتخب کریں۔' },
  accountNumberRequired: { en: 'Account number is required.', ur: 'اکاؤنٹ نمبر ضروری ہے۔' },
  accountNameRequired: { en: 'Account name is required.', ur: 'اکاؤنٹ کا نام ضروری ہے۔' },
  setBidEndTime: { en: 'Please set bid end time.', ur: 'براہ کرم بولی ختم ہونے کا وقت سیٹ کریں۔' },
  basePriceRequired: { en: 'Base price is required.', ur: 'بنیادی قیمت ضروری ہے۔' },
  basePriceMustBeNumber: { en: 'Base price must be a number.', ur: 'بنیادی قیمت ایک عدد ہونی چاہیے۔' },
  cropListedSuccess: { en: 'Your Crop Listed Successfully! 🌾', ur: 'آپ کی فصل کامیابی سے لسٹ ہوگئی! 🌾' },
  limitReached: { en: 'Limit Reached', ur: 'حد پوری ہوگئی' },
  maxThreeImages: { en: 'You can upload maximum 3 images.', ur: 'آپ زیادہ سے زیادہ 3 تصاویر اپلوڈ کر سکتے ہیں۔' },
  locationCapturedToast: { en: '📍 Live location captured!', ur: '📍 لائیو مقام محفوظ ہوگیا!' },
  soldOut: { en: 'Sold Out', ur: 'فروخت ہوگیا' },
  active: { en: 'Active', ur: 'فعال' },
  ended: { en: 'Ended', ur: 'ختم' },

  // Farmer Funding
  funding: { en: 'Funding', ur: 'فنڈنگ' },
  postLandForFunding: { en: 'Post Land for Funding', ur: 'فنڈنگ کے لیے زمین پوسٹ کریں' },
  connectWithInvestors: { en: 'Connect with investors for your land', ur: 'اپنی زمین کے لیے سرمایہ کاروں سے جڑیں' },
  landImages: { en: '📸 Land Images (Max 3)', ur: '📸 زمین کی تصاویر (زیادہ سے زیادہ 3)' },
  landAreaTitle: { en: 'Land Area Title', ur: 'زمینی علاقے کا عنوان' },
  enterLandTitle: { en: 'Enter Your title', ur: 'اپنا عنوان درج کریں' },
  description: { en: 'Description', ur: 'تفصیل' },
  describeLand: { en: 'Describe the land area in detail...', ur: 'زمینی علاقے کی تفصیل بیان کریں...' },
  enterCityLabel: { en: 'Enter City', ur: 'شہر درج کریں' },
  enterCompleteAddressLabel: { en: 'Enter complete address', ur: 'مکمل پتہ درج کریں' },
  investorsWillSeeLocation: { en: 'Investors will see your exact farm location on Google Maps', ur: 'سرمایہ کار گوگل میپ پر آپ کا کھیت دیکھ سکیں گے' },
  submitLandListing: { en: '🚀 Submit Land Listing', ur: '🚀 زمین کی لسٹنگ جمع کریں' },
  yourLandListings: { en: 'Your Land Listings', ur: 'آپ کی زمین کی لسٹنگز' },
  pleaseUploadLandImage: { en: 'Please upload at least 1 land image.', ur: 'براہ کرم کم از کم 1 زمین کی تصویر اپلوڈ کریں۔' },
  landTitleRequired: { en: 'Land title is required.', ur: 'زمین کا عنوان ضروری ہے۔' },
  landListedSuccess: { en: 'Your Land Area Listed Successfully! 🌍', ur: 'آپ کی زمین کامیابی سے لسٹ ہوگئی! 🌍' },
  soldOutStatus: { en: '🔴 Sold Out', ur: '🔴 فروخت ہوگیا' },
  activeStatus: { en: '🟢 Active', ur: '🟢 فعال' },

  // Farmer Item List
  itemList: { en: 'Item List', ur: 'اشیاء کی فہرست' },
  crops: { en: 'Crops', ur: 'فصلیں' },
  land: { en: 'Land', ur: 'زمین' },
  noCropsListed: { en: 'No Crops Listed', ur: 'کوئی فصل لسٹ نہیں' },
  noLandListed: { en: 'No Land Listed', ur: 'کوئی زمین لسٹ نہیں' },
  goToDashboard: { en: 'Go to Dashboard to add your first listing.', ur: 'پہلی لسٹنگ شامل کرنے کے لیے ڈیش بورڈ پر جائیں۔' },
  goToFunding: { en: 'Go to Funding to add your first listing.', ur: 'پہلی لسٹنگ شامل کرنے کے لیے فنڈنگ پر جائیں۔' },
  cropSoldOut: { en: '🔴 This Crop is Sold out', ur: '🔴 یہ فصل فروخت ہوگئی' },
  landSoldOut: { en: '🔴 This Land is Sold out', ur: '🔴 یہ زمین فروخت ہوگئی' },
  editBtn: { en: '✏️ Edit', ur: '✏️ ترمیم' },
  deleteBtn: { en: '🗑️ Delete', ur: '🗑️ حذف کریں' },
  saleOutBtn: { en: '💰 Sale Out', ur: '💰 فروخت' },
  soldBtn: { en: '✔ Sold', ur: '✔ فروخت ہوا' },
  deletePost: { en: 'Delete Post', ur: 'پوسٹ حذف کریں' },
  deleteConfirmCrop: { en: 'Are you sure you want to delete this crop listing?', ur: 'کیا آپ واقعی اس فصل کی لسٹنگ حذف کرنا چاہتے ہیں؟' },
  deleteConfirmLand: { en: 'Are you sure you want to delete this land listing?', ur: 'کیا آپ واقعی اس زمین کی لسٹنگ حذف کرنا چاہتے ہیں؟' },
  cancelLabel: { en: 'Cancel', ur: 'منسوخ کریں' },
  deleteLabel: { en: 'Delete', ur: 'حذف کریں' },
  cropDeleteSuccess: { en: 'Crop delete successfully', ur: 'فصل کامیابی سے حذف ہوگئی' },
  landDeleteSuccess: { en: 'Land listing deleted successfully', ur: 'زمین کی لسٹنگ کامیابی سے حذف ہوگئی' },
  cropSaleSuccess: { en: 'Your crop Sale Successfully', ur: 'آپ کی فصل کامیابی سے فروخت ہوگئی' },
  editListing: { en: 'Edit Listing', ur: 'لسٹنگ میں ترمیم کریں' },
  cancelEditListing: { en: '← Cancel', ur: '← منسوخ کریں' },
  images: { en: 'Images', ur: 'تصاویر' },
  titleLabel: { en: 'Title', ur: 'عنوان' },
  updateListing: { en: '💾 Update Listing', ur: '💾 لسٹنگ اپڈیٹ کریں' },
  editSuccess: { en: 'Edit successfully', ur: 'ترمیم کامیابی سے ہوگئی' },
  maxImagesAllowed: { en: 'Max 3 images allowed.', ur: 'زیادہ سے زیادہ 3 تصاویر ہو سکتی ہیں۔' },
  add: { en: 'Add', ur: 'شامل کریں' },
  cityField: { en: 'City', ur: 'شہر' },
  addressField: { en: 'Address', ur: 'پتہ' },

  // Farmer History
  history: { en: 'History', ur: 'تاریخ' },
  noHistoryYet: { en: 'No History Yet', ur: 'ابھی کوئی تاریخ نہیں' },
  historySubtitle: { en: 'Your crop listing history will appear here.', ur: 'آپ کی فصل لسٹنگ کی تاریخ یہاں نظر آئے گی۔' },
  base: { en: 'Base:', ur: 'بنیاد:' },
  wonAt: { en: 'Won at PKR', ur: 'جیتا PKR پر' },
  noOneInterested: { en: 'No one is interested', ur: 'کوئی دلچسپی نہیں رکھتا' },
  viewProfile: { en: 'View Profile', ur: 'پروفائل دیکھیں' },
  phoneLabel: { en: 'Phone', ur: 'فون' },
  cityFieldLabel: { en: 'City', ur: 'شہر' },
  addressFieldLabel: { en: 'Address', ur: 'پتہ' },
  accountNumberField: { en: 'Account Number', ur: 'اکاؤنٹ نمبر' },
  buyerProfile: { en: 'Buyer Profile', ur: 'خریدار کی پروفائل' },

  // Farmer Payment
  payment: { en: 'Payment', ur: 'ادائیگی' },
  noPaymentsYet: { en: 'No Payments Yet', ur: 'ابھی کوئی ادائیگی نہیں' },
  paymentsSubtitle: { en: "When buyers confirm payment, they'll appear here.", ur: 'جب خریدار ادائیگی کی تصدیق کریں گے، وہ یہاں نظر آئیں گے۔' },
  paymentDetails: { en: 'Payment Details', ur: 'ادائیگی کی تفصیلات' },
  buyerConfirmDetails: { en: 'Buyer Confirmation Details', ur: 'خریدار کی تصدیقی تفصیلات' },
  fullName: { en: 'Full Name', ur: 'پورا نام' },
  paymentMethodLabel: { en: 'Payment Method', ur: 'ادائیگی کا طریقہ' },
  accountNumberPay: { en: 'Account Number', ur: 'اکاؤنٹ نمبر' },
  accountNamePay: { en: 'Account Name', ur: 'اکاؤنٹ کا نام' },
  rateThisBuyer: { en: 'Rate This Buyer', ur: 'اس خریدار کو ریٹ کریں' },
  deliveryTimeDays: { en: 'Delivery Time (Days)', ur: 'ڈیلیوری کا وقت (دن)' },
  enterDeliveryDays: { en: 'Enter number of days', ur: 'دنوں کی تعداد درج کریں' },
  daysLabel: { en: 'Days', ur: 'دن' },
  cancelOrder: { en: '✕ Cancel Order', ur: '✕ آرڈر منسوخ کریں' },
  confirmDelivery: { en: '✓ Confirm Delivery', ur: '✓ ڈیلیوری کی تصدیق کریں' },
  deliveryConfirmed: { en: 'Delivery confirmed! Buyer notified.', ur: 'ڈیلیوری کی تصدیق ہوگئی! خریدار کو مطلع کیا گیا۔' },
  enterDeliveryDaysToast: { en: 'Please enter delivery days.', ur: 'براہ کرم ڈیلیوری کے دن درج کریں۔' },
  orderCancelledToast: { en: 'Order cancelled. Bidding restarted.', ur: 'آرڈر منسوخ ہوگیا۔ بولی دوبارہ شروع ہوئی۔' },
  paid: { en: '💚 Paid', ur: '💚 ادا ہوگئی' },

  // Farmer Complain + shared Complain
  complain: { en: 'Complain', ur: 'شکایت' },
  submitComplaint: { en: 'Submit a Complaint', ur: 'شکایت جمع کریں' },
  forwardToAdmin: { en: "We'll forward it to Admin immediately", ur: 'ہم اسے فوری طور پر ایڈمن کو بھیجیں گے' },
  problemTitle: { en: 'Problem Title', ur: 'مسئلے کا عنوان' },
  problemTitlePlaceholder: { en: 'Problem Title', ur: 'مسئلے کا عنوان' },
  describeProblem: { en: 'Describe Your Problem in Detail', ur: 'اپنا مسئلہ تفصیل سے بیان کریں' },
  describeProblemPlaceholder: { en: 'Describe your problem in details', ur: 'اپنا مسئلہ تفصیل سے بیان کریں' },
  uploadScreenshots: { en: 'Upload Screenshots (Max 3)', ur: 'اسکرین شاٹس اپلوڈ کریں (زیادہ سے زیادہ 3)' },
  screenshotHint: { en: 'Upload at least 1 screenshot. Upload 1 to reveal next slot.', ur: 'کم از کم 1 اسکرین شاٹ اپلوڈ کریں۔' },
  addScreenshot: { en: 'Add Screenshot', ur: 'اسکرین شاٹ شامل کریں' },
  submitComplaintBtn: { en: '📤 Submit Complaint', ur: '📤 شکایت جمع کریں' },
  complaintSubmitted: { en: 'Complaint Submitted!', ur: 'شکایت جمع ہوگئی!' },
  complaintSubmittedMsg: { en: 'Your complaint Submit to Admin Successfully.', ur: 'آپ کی شکایت کامیابی سے ایڈمن کو بھیج دی گئی۔' },
  okay: { en: 'Okay', ur: 'ٹھیک ہے' },
  problemTitleRequired: { en: 'Problem title is required.', ur: 'مسئلے کا عنوان ضروری ہے۔' },
  problemDetailRequired: { en: 'Please describe your problem.', ur: 'براہ کرم اپنا مسئلہ بیان کریں۔' },
  screenshotRequired: { en: 'At least one screenshot is required.', ur: 'کم از کم ایک اسکرین شاٹ ضروری ہے۔' },

  // Buyer Home
  buyerHome: { en: 'Home', ur: 'ہوم' },
  availableCrops: { en: '🌾 Available Crops', ur: '🌾 دستیاب فصلیں' },
  noCropsAvailable: { en: 'No Crops Available', ur: 'کوئی فصل دستیاب نہیں' },
  noCropsSubtitle: { en: 'Farmers will post their crops here.', ur: 'کسان یہاں اپنی فصلیں پوسٹ کریں گے۔' },
  bidNow: { en: 'Bid Now', ur: 'ابھی بولی لگائیں' },
  bidEndsIn: { en: 'Bid ends in:', ur: 'بولی ختم ہوگی:' },
  basePriceLabel: { en: 'Base Price:', ur: 'بنیادی قیمت:' },
  highestBid: { en: 'Highest Bid:', ur: 'سب سے زیادہ بولی:' },
  totalBids: { en: 'Total Bids:', ur: 'کل بولیاں:' },
  yourBid: { en: 'Your Bid', ur: 'آپ کی بولی' },
  enterBidAmount: { en: 'Enter bid amount (PKR)', ur: 'بولی کی رقم درج کریں (روپے)' },
  placeBid: { en: 'Place Bid', ur: 'بولی لگائیں' },
  cancelBid: { en: 'Cancel Bid', ur: 'بولی منسوخ کریں' },
  confirmPayment: { en: 'Confirm Payment', ur: 'ادائیگی کی تصدیق کریں' },
  bidPlaced: { en: 'Bid placed successfully!', ur: 'بولی کامیابی سے لگائی گئی!' },
  bidCancelled: { en: 'Bid cancelled.', ur: 'بولی منسوخ ہوگئی۔' },
  soldOutLabel: { en: '🔴 Sold Out', ur: '🔴 فروخت ہوگیا' },
  viewLocation: { en: '📍 View Location', ur: '📍 مقام دیکھیں' },
  rateThisFarmer: { en: 'Rate This Farmer', ur: 'اس کسان کو ریٹ کریں' },
  submitReview: { en: 'Submit Review', ur: 'جائزہ جمع کریں' },
  reviewTitle: { en: 'Review Title', ur: 'جائزے کا عنوان' },
  reviewDetail: { en: 'Review Detail', ur: 'جائزے کی تفصیل' },
  paymentConfirmed: { en: 'Payment confirmed!', ur: 'ادائیگی کی تصدیق ہوگئی!' },
  searchCropsCity: { en: 'Search crops or city...', ur: 'فصل یا شہر تلاش کریں...' },
  noResultsFound: { en: 'No Results Found', ur: 'کوئی نتیجہ نہیں ملا' },
  noCropsYet: { en: 'No Crops Listed Yet', ur: 'ابھی کوئی فصل لسٹ نہیں' },
  checkBackLater: { en: 'Farmers will list crops soon. Check back later!', ur: 'کسان جلد فصلیں لسٹ کریں گے۔ بعد میں دیکھیں!' },
  seeFarmerLocation: { en: '📍 See Farmer Live Location', ur: '📍 کسان کا لائیو مقام دیکھیں' },
  farmerProfile: { en: 'Farmer Profile', ur: 'کسان کی پروفائل' },
  updateBid: { en: '⬆ Update Bid', ur: '⬆ بولی اپڈیٹ کریں' },
  updateBidTitle: { en: 'Update Your Bid', ur: 'اپنی بولی اپڈیٹ کریں' },
  placeABid: { en: 'Place a Bid', ur: 'بولی لگائیں' },
  confirmBid: { en: '🏷️ Confirm Bid', ur: '🏷️ بولی کی تصدیق کریں' },
  enterBidAmountPKR: { en: 'Enter Your Bid Amount (PKR)', ur: 'اپنی بولی کی رقم درج کریں (روپے)' },
  cancelBidQ: { en: 'Cancel Bid?', ur: 'بولی منسوخ کریں؟' },
  cancelBidConfirm: { en: 'Are you sure you want to cancel your bid on', ur: 'کیا آپ واقعی اس پر اپنی بولی منسوخ کرنا چاہتے ہیں' },
  keepBid: { en: 'Keep Bid', ur: 'بولی رکھیں' },
  yesCancel: { en: 'Yes, Cancel', ur: 'ہاں، منسوخ کریں' },
  youWon: { en: '🏆 You Won! Go to Orders to confirm payment.', ur: '🏆 آپ جیت گئے! ادائیگی کی تصدیق کے لیے آرڈرز پر جائیں۔' },
  writeAReview: { en: 'Write a Review', ur: 'جائزہ لکھیں' },
  giveReview: { en: '⭐ Give Review', ur: '⭐ جائزہ دیں' },
  cancelReview: { en: '✕ Cancel Review', ur: '✕ جائزہ منسوخ کریں' },
  submitReviewBtn: { en: '📤 Submit Review', ur: '📤 جائزہ جمع کریں' },
  reviewsCount: { en: 'reviews', ur: 'جائزے' },

  // Buyer Orders
  orders: { en: 'Orders', ur: 'آرڈرز' },
  noOrdersYet: { en: 'No Orders Yet', ur: 'ابھی کوئی آرڈر نہیں' },
  ordersSubtitle: { en: "Orders from your confirmed bids will appear here.", ur: 'آپ کی تصدیق شدہ بولیوں کے آرڈرز یہاں نظر آئیں گے۔' },
  orderDetails: { en: 'Order Details', ur: 'آرڈر کی تفصیلات' },
  ordersAndFunding: { en: 'Orders & Funding', ur: 'آرڈرز اور فنڈنگ' },
  myOrders: { en: '📦 My Orders', ur: '📦 میرے آرڈرز' },
  fundingTab: { en: '💰 Funding', ur: '💰 فنڈنگ' },
  wonAuctions: { en: '🏆 Won Auctions', ur: '🏆 جیتی ہوئی نیلامیاں' },
  noWonAuctions: { en: 'No won auctions yet. Keep bidding!', ur: 'ابھی کوئی نیلامی نہیں جیتی۔ بولی لگاتے رہیں!' },
  activeBids: { en: '🏷️ Active Bids', ur: '🏷️ فعال بولیاں' },
  noActiveBids: { en: 'No active bids. Browse crops to start bidding!', ur: 'کوئی فعال بولی نہیں۔ بولی لگانے کے لیے فصلیں دیکھیں!' },
  wonAt2: { en: '🏆 Won at PKR', ur: '🏆 جیتا PKR پر' },
  farmerLabel: { en: 'Farmer:', ur: 'کسان:' },
  payVia: { en: 'Pay via:', ur: 'ادائیگی:' },
  accountLabel: { en: 'Account:', ur: 'اکاؤنٹ:' },
  nameLabel: { en: 'Name:', ur: 'نام:' },
  confirmPay: { en: '💳 Confirm Pay', ur: '💳 ادائیگی کی تصدیق کریں' },
  alreadyPaid: { en: '✅ Paid', ur: '✅ ادا ہوگئی' },
  yourBidLabel: { en: 'Your Bid:', ur: 'آپ کی بولی:' },
  youLeading: { en: "🥇 You're leading!", ur: '🥇 آپ آگے ہیں!' },
  outbidBy: { en: '⬇ Outbid by PKR', ur: '⬇ پیچھے PKR سے' },
  noLandListings: { en: 'No Land Listings', ur: 'کوئی زمین لسٹنگ نہیں' },
  noLandListingsSubtitle: { en: "Farmers haven't listed any land for funding yet.", ur: 'کسانوں نے ابھی کوئی زمین فنڈنگ کے لیے لسٹ نہیں کی۔' },
  interestedToFund: { en: "💼 I'm Interested to Fund", ur: '💼 میں فنڈ کرنے میں دلچسپی رکھتا ہوں' },
  confirmPaymentTitle: { en: '💳 Confirm Payment', ur: '💳 ادائیگی کی تصدیق کریں' },
  paymentInstruction: { en: "Please transfer the amount to the farmer's account above, then fill in your details below:", ur: 'براہ کرم اوپر دیے گئے کسان کے اکاؤنٹ میں رقم منتقل کریں، پھر اپنی تفصیلات نیچے درج کریں:' },
  yourFullName: { en: 'Your Full Name', ur: 'آپ کا پورا نام' },
  phoneNumber2: { en: 'Phone Number', ur: 'فون نمبر' },
  city2: { en: 'City', ur: 'شہر' },
  deliveryAddress: { en: 'Complete Delivery Address', ur: 'مکمل ڈیلیوری پتہ' },
  confirmNotifyFarmer: { en: '✅ Confirm & Notify Farmer', ur: '✅ تصدیق کریں اور کسان کو مطلع کریں' },
  paymentAlreadyConfirmed: { en: '✅ Payment already confirmed!', ur: '✅ ادائیگی پہلے سے تصدیق شدہ ہے!' },
  expressInterestTitle: { en: '💼 Express Interest', ur: '💼 دلچسپی ظاہر کریں' },
  fillContactDetails: { en: 'Fill in your contact details and the farmer will reach out to you to discuss funding terms.', ur: 'اپنی رابطے کی تفصیلات بھریں اور کسان فنڈنگ کی شرائط پر بات کرنے کے لیے آپ سے رابطہ کرے گا۔' },
  submitInterest: { en: '📤 Submit Interest', ur: '📤 دلچسپی جمع کریں' },
  interestSubmitted: { en: 'Interest Submitted!', ur: 'دلچسپی جمع ہوگئی!' },
  interestSubmittedMsg: { en: 'The farmer has been notified of your interest.\nThey will contact you shortly.', ur: 'کسان کو آپ کی دلچسپی کے بارے میں مطلع کر دیا گیا ہے۔\nوہ جلد آپ سے رابطہ کریں گے۔' },
  done: { en: 'Done', ur: 'ہو گیا' },
  fullNameRequired: { en: 'Full name required.', ur: 'پورا نام ضروری ہے۔' },
  phoneRequired2: { en: 'Phone required.', ur: 'فون نمبر ضروری ہے۔' },
  cityRequired3: { en: 'City required.', ur: 'شہر ضروری ہے۔' },
  addressRequired3: { en: 'Address required.', ur: 'پتہ ضروری ہے۔' },
  enterFullName: { en: 'Enter full name', ur: 'پورا نام درج کریں' },
  enterPhoneNumber: { en: 'Enter phone number', ur: 'فون نمبر درج کریں' },
  enterCityField: { en: 'Enter city', ur: 'شہر درج کریں' },
  enterDeliveryAddressField: { en: 'Enter your delivery address', ur: 'اپنا ڈیلیوری پتہ درج کریں' },
  enterAddressField: { en: 'Enter your address', ur: 'اپنا پتہ درج کریں' },
  paymentConfirmedToast: { en: '✅ Payment confirmed! Farmer has been notified.', ur: '✅ ادائیگی کی تصدیق ہوگئی! کسان کو مطلع کیا گیا۔' },

  // Investor Home
  investorHome: { en: 'Home', ur: 'ہوم' },
  availableLand: { en: '🌍 Available Land', ur: '🌍 دستیاب زمین' },
  noLandAvailable: { en: 'No Land Available', ur: 'کوئی زمین دستیاب نہیں' },
  noLandSubtitle: { en: 'Farmers will post their land here.', ur: 'کسان یہاں اپنی زمین پوسٹ کریں گے۔' },
  expressInterest: { en: 'Express Interest', ur: 'دلچسپی ظاہر کریں' },
  interestedLabel: { en: '✅ Interested', ur: '✅ دلچسپی ہے' },
  interestSent: { en: 'Interest sent to farmer!', ur: 'دلچسپی کسان کو بھیج دی گئی!' },
  searchLandCity: { en: 'Search land area or city...', ur: 'زمین یا شہر تلاش کریں...' },
  noResultsFoundLabel: { en: 'No Results Found', ur: 'کوئی نتیجہ نہیں ملا' },
  noLandListingsLabel: { en: 'No Land Listings', ur: 'کوئی زمین لسٹنگ نہیں' },
  farmersWillListSoon: { en: 'Farmers will list land for funding soon.', ur: 'کسان جلد فنڈنگ کے لیے زمین لسٹ کریں گے۔' },
  moreInfo: { en: 'More Info →', ur: 'مزید معلومات ←' },
  backLabel: { en: '← Back', ur: '→ واپس' },
  seeFarmerLiveLocation: { en: '📍 See Farmer Live Location', ur: '📍 کسان کا لائیو مقام دیکھیں' },
  messageFarmer: { en: '💬 Message Farmer', ur: '💬 کسان کو پیغام کریں' },
  noMessagesStartConversation: { en: 'No messages yet. Start the conversation!', ur: 'ابھی کوئی پیغام نہیں۔ گفتگو شروع کریں!' },
  writeAReviewInvestor: { en: '⭐ Write a Review', ur: '⭐ جائزہ لکھیں' },
  yourReview: { en: 'Your Review', ur: 'آپ کا جائزہ' },
  editReview: { en: '✏️ Edit Review', ur: '✏️ جائزہ ترمیم کریں' },
  deleteReview: { en: '🗑️ Delete', ur: '🗑️ حذف کریں' },
  deleteReviewTitle: { en: 'Delete Review', ur: 'جائزہ حذف کریں' },
  deleteReviewConfirm: { en: 'Are you sure you want to delete this review?', ur: 'کیا آپ واقعی یہ جائزہ حذف کرنا چاہتے ہیں؟' },
  reviewUpdated: { en: '✅ Your review has been updated.', ur: '✅ آپ کا جائزہ اپڈیٹ ہوگیا۔' },
  reviewPosted: { en: '✅ Your review has been posted.', ur: '✅ آپ کا جائزہ پوسٹ ہوگیا۔' },
  reviewDeleted: { en: '🗑️ Your review has been deleted.', ur: '🗑️ آپ کا جائزہ حذف ہوگیا۔' },
  updateReview: { en: '💾 Update Review', ur: '💾 جائزہ اپڈیٹ کریں' },
  postReview: { en: '📤 Post Review', ur: '📤 جائزہ پوسٹ کریں' },
  allReviews: { en: 'All Reviews', ur: 'تمام جائزے' },
  viewAllReviews: { en: 'View All Reviews', ur: 'تمام جائزے دیکھیں' },
  showLess: { en: 'Show Less', ur: 'کم دکھائیں' },
  ratingRequired: { en: 'Please select a rating.', ur: 'براہ کرم ریٹنگ منتخب کریں۔' },
  reviewTitleRequired: { en: 'Title is required.', ur: 'عنوان ضروری ہے۔' },
  reviewDetailRequired: { en: 'Detail is required.', ur: 'تفصیل ضروری ہے۔' },
  shortSummary: { en: 'Short summary...', ur: 'مختصر خلاصہ...' },
  yourExperience: { en: 'Your experience with this farmer...', ur: 'اس کسان کے ساتھ آپ کا تجربہ...' },

  // Mandi Screen
  provinceAll: { en: 'All', ur: 'سب' },
  provincePunjab: { en: 'Punjab', ur: 'پنجاب' },
  provinceSindh: { en: 'Sindh', ur: 'سندھ' },
  provinceKPK: { en: 'KPK', ur: 'خیبرپختونخواہ' },
  provinceBalochistan: { en: 'Balochistan', ur: 'بلوچستان' },
  mandiAlertPlaceholder: { en: 'Enter threshold price', ur: 'حد قیمت درج کریں' },
  mandiAlertRemove: { en: '🗑️ Remove', ur: '🗑️ ہٹائیں' },
  mandiSyncCached: { en: 'Cached', ur: 'محفوظ شدہ' },
  mandiSyncLive: { en: 'Live', ur: 'لائیو' },
  mandiXToday: { en: 'Today', ur: 'آج' },
  mandiChartHint: { en: '← Scroll to explore all dates  •  Prices in PKR per maan', ur: '← تمام تاریخیں دیکھنے کے لیے سکرول کریں  •  قیمتیں PKR فی من' },
  mandiMoreResults: { en: 'more results', ur: 'مزید نتائج' },

  // Investment Guideline Screen
  investmentGuidelineTitle: { en: 'Investment Guideline', ur: 'سرمایہ کاری رہنما' },
  investmentGuidelineHeroTitle: { en: 'Smart Investment Guidelines', ur: 'ذہین سرمایہ کاری کے اصول' },
  investmentGuidelineHeroSub: { en: "Follow these key principles before investing in any farmer's land", ur: 'کسی بھی کسان کی زمین میں سرمایہ کاری سے پہلے ان اہم اصولوں پر عمل کریں' },
  investmentGuidelineIntro: { en: "Before investing in a farmer's land, carefully evaluate whether the land and the farmer have strong potential for a safe and profitable return.", ur: 'کسان کی زمین میں سرمایہ کاری سے پہلے، یہ احتیاط سے جائزہ لیں کہ آیا زمین اور کسان میں محفوظ اور منافع بخش واپسی کی مضبوط صلاحیت ہے۔' },
  investmentGuidelineGoldenRule: { en: '✅ Golden Rule of Investment', ur: '✅ سرمایہ کاری کا سنہری اصول' },
  investmentGuidelineSummary1: { en: '🌱  The land must be productive', ur: '🌱  زمین زرخیز ہونی چاہیے' },
  investmentGuidelineSummary2: { en: '🤝  The farmer must be reliable', ur: '🤝  کسان قابل اعتماد ہونا چاہیے' },
  investmentGuidelineSummary3: { en: '📈  The crop must have market potential', ur: '📈  فصل میں مارکیٹ کی صلاحیت ہونی چاہیے' },
  investmentGuidelineSummary4: { en: '⚖️  The overall risk must be manageable', ur: '⚖️  مجموعی خطرہ قابل انتظام ہونا چاہیے' },
  investmentGuidelineSummaryFooter: { en: 'Good investment decisions should be based on both opportunity and caution.', ur: 'اچھے سرمایہ کاری فیصلے موقع اور احتیاط دونوں پر مبنی ہونے چاہئیں۔' },
  investmentGuidelineContact: { en: 'For more guidelines, contact ', ur: 'مزید رہنما اصولوں کے لیے رابطہ کریں ' },
  investmentGuidelineWarning: { en: 'Please send payment to Farm Nest Admin account only. Double-check all details before sending.', ur: 'براہ کرم ادائیگی صرف Farm Nest ایڈمن اکاؤنٹ میں بھیجیں۔ بھیجنے سے پہلے تمام تفصیلات دوبارہ چیک کریں۔' },

  // Daily limit banner & modal
  dailyLimitInfo: { en: 'You can only create 3 posts per day. You cannot create more than this.', ur: 'آپ صرف روزانہ 3 پوسٹ بنا سکتے ہیں۔ اس سے زیادہ نہیں بنا سکتے۔' },
  postsToday: { en: 'Posts today:', ur: 'آج کی پوسٹس:' },
  dailyLimitReachedTitle: { en: 'Daily Limit Reached', ur: 'روزانہ کی حد پوری ہوگئی' },
  dailyLimitReachedBody: { en: 'You have reached your daily limit of 3 posts.', ur: 'آپ نے روزانہ کی 3 پوسٹس کی حد پوری کرلی ہے۔' },
  dailyLimitResetOn: { en: 'Your limit will reset on', ur: 'آپ کی حد دوبارہ ہوگی' },
  dailyLimitTimeRemaining: { en: 'Time remaining:', ur: 'باقی وقت:' },

  // Buyer Home extra
  biddingEnded: { en: '⛔ Bidding Ended', ur: '⛔ بولی ختم ہوگئی' },
  messageFarmerBtn: { en: '💬 Message', ur: '💬 پیغام' },
  messageFarmerAlone: { en: '💬 Message Farmer', ur: '💬 کسان کو پیغام کریں' },
  approveLabel: { en: 'Approve', ur: 'منظور کریں' },

  // Buyer Order Screen extra
  clickNow: { en: 'Click Now', ur: 'ابھی کلک کریں' },
  payWithinTime: { en: '⏱ Pay within:', ur: '⏱ وقت پر ادائیگی کریں:' },
  paymentTimeExpired: { en: '⛔ Payment Time Expired', ur: '⛔ ادائیگی کا وقت ختم ہوگیا' },
  paymentWarning: { en: '⚠️ You must confirm payment within 24 hours of winning. If payment is not made in time, your order will be automatically canceled and the item will go back to bidding.', ur: '⚠️ جیتنے کے 24 گھنٹوں کے اندر ادائیگی کی تصدیق کرنا ضروری ہے۔ اگر وقت پر ادائیگی نہ ہوئی تو آپ کا آرڈر خودکار طور پر منسوخ ہوجائے گا اور آئٹم دوبارہ بولی میں چلا جائے گا۔' },
  paymentTimerSetup: { en: '⏳ 24h payment timer is being set up...', ur: '⏳ 24 گھنٹے کا ادائیگی ٹائمر ترتیب دیا جا رہا ہے...' },
  paymentConfirmationTitle: { en: 'Payment Confirmation', ur: 'ادائیگی کی تصدیق' },
  paymentConfirmationMsg: { en: "The payment will be transferred to Farm Nest Admin's account. Please carefully check the name and details before sending the payment. Farm Nest will not be responsible for any incorrect payment.", ur: 'ادائیگی Farm Nest ایڈمن اکاؤنٹ میں منتقل ہوگی۔ براہ کرم ادائیگی بھیجنے سے پہلے نام اور تفصیلات احتیاط سے چیک کریں۔ Farm Nest کسی غلط ادائیگی کی ذمہ دار نہیں ہوگی۔' },
  iUnderstand: { en: 'I Understand', ur: 'میں سمجھ گیا' },
  paymentDetailsTitle: { en: 'Payment Details', ur: 'ادائیگی کی تفصیلات' },
  mobileWallets: { en: 'Mobile Wallets', ur: 'موبائل والٹ' },
  bankAccounts: { en: 'Bank Accounts', ur: 'بینک اکاؤنٹس' },
  accountNameLabel: { en: 'Account Name', ur: 'اکاؤنٹ کا نام' },
  accountNumberDetail: { en: 'Account Number', ur: 'اکاؤنٹ نمبر' },
  ibanLabel: { en: 'IBAN', ur: 'IBAN' },
  paymentSentSelf: { en: 'You have sent the payment to Farm Nest account.', ur: 'آپ نے Farm Nest اکاؤنٹ میں ادائیگی بھیج دی ہے۔' },
  paymentSentFarmer: { en: 'The buyer has sent the payment to Farm Nest account. The amount will remain on hold for 7 days.', ur: 'خریدار نے Farm Nest اکاؤنٹ میں ادائیگی بھیج دی ہے۔ رقم 7 دن کے لیے ہولڈ پر رہے گی۔' },
  paymentAmountLabel: { en: 'Amount: PKR ', ur: 'رقم: PKR ' },
  backBtn: { en: '<- Back', ur: '-> واپس' },
  amountLabel: { en: 'Amount: PKR ', ur: 'رقم: PKR ' },
  cancelOrderNotif: { en: 'Your order was automatically canceled because payment was not made within 24 hours.', ur: 'آپ کا آرڈر خودکار طور پر منسوخ ہوگیا کیونکہ 24 گھنٹوں میں ادائیگی نہیں ہوئی۔' },
  fileError: { en: 'Please upload the required file.', ur: 'براہ کرم مطلوبہ فائل اپلوڈ کریں۔' },

  // Investor Home - Your Rating
  yourRatingLabel: { en: 'Your Rating', ur: 'آپ کی ریٹنگ' },

  // Notifications detail modal
  notifDetailTitle: { en: '🔔 Notification', ur: '🔔 اطلاع' },
  notifReceived: { en: '🕐 Received', ur: '🕐 موصول ہوئی' },
  notifRead: { en: '✓ Read', ur: '✓ پڑھی گئی' },
  notifUnread: { en: '● Unread', ur: '● نہیں پڑھی' },

  // Penalty Card & Modal (Buyer Profile + Farmer view of buyer)
  penaltyStatus: { en: '⚠️ Penalty Status', ur: '⚠️ جرمانے کی حیثیت' },
  penaltiesReceived: { en: 'penalties received', ur: 'جرمانے ملے' },
  penaltyAccountSuspendWarning: { en: '🚫 Your account may be suspended after 3 penalties.', ur: '🚫 3 جرمانوں کے بعد آپ کا اکاؤنٹ معطل ہو سکتا ہے۔' },
  penaltyInfoLink: { en: 'What are penalties? Tap to learn more', ur: 'جرمانے کیا ہیں؟ مزید جاننے کے لیے ٹیپ کریں' },
  penaltySystemTitle: { en: '⚠️ Penalty System', ur: '⚠️ جرمانہ نظام' },
  penaltySystemBody: { en: 'If you have received a penalty, it means you either cancelled an order after winning a bid, or failed to send the payment to the Farmnest account within 24 hours.', ur: 'اگر آپ کو جرمانہ ملا ہے، تو اس کا مطلب ہے کہ آپ نے بولی جیتنے کے بعد آرڈر منسوخ کیا، یا 24 گھنٹوں میں Farmnest اکاؤنٹ میں ادائیگی نہیں بھیجی۔' },
  penaltyFirst: { en: '• 1st penalty: Warning', ur: '• پہلا جرمانہ: تنبیہ' },
  penaltySecond: { en: '• 2nd penalty: Warning', ur: '• دوسرا جرمانہ: تنبیہ' },
  penaltyThird: { en: '• 3rd consecutive penalty: Account automatically suspended', ur: '• تیسرا لگاتار جرمانہ: اکاؤنٹ خودکار طور پر معطل' },
  penaltyGotIt: { en: 'Got it', ur: 'سمجھ گیا' },
  penaltyBuyerHas: { en: 'This buyer has received', ur: 'اس خریدار کو' },
  penaltyBuyerHasSuffix: { en: 'penalty/penalties.', ur: 'جرمانے ملے ہیں۔' },

  // Suspended Screen
  accountSuspendedTitle: { en: 'Account Suspended', ur: 'اکاؤنٹ معطل ہوگیا' },
  accountSuspendedMsg: { en: 'Your account has been suspended by the Admin. You can no longer access this platform.', ur: 'آپ کا اکاؤنٹ ایڈمن نے معطل کردیا ہے۔ آپ اب اس پلیٹ فارم تک رسائی حاصل نہیں کر سکتے۔' },
  accountSuspendedSub: { en: 'If you believe this is a mistake, please contact support.', ur: 'اگر آپ کو لگتا ہے کہ یہ غلطی ہے تو براہ کرم سپورٹ سے رابطہ کریں۔' },
  backToLogin: { en: 'Back to Login', ur: 'لاگ ان پر واپس جائیں' },

  // Email Verification (after Registration)
  evTitle:        { en: 'Verify Your Email', ur: 'اپنی ای میل تصدیق کریں' },
  evSubtitle:     { en: 'A 10-character code has been sent to your email. Enter it below to verify your account.', ur: 'آپ کی ای میل پر 10 حروف کا کوڈ بھیجا گیا ہے۔ اکاؤنٹ تصدیق کرنے کے لیے نیچے درج کریں۔' },
  evSentTo:       { en: 'A verification code was sent to', ur: 'تصدیقی کوڈ بھیجا گیا' },
  evVerifyBtn:    { en: '✅ Verify & Continue', ur: '✅ تصدیق کریں اور جاری رکھیں' },
  evSkip:         { en: 'Skip for now → Go to Login', ur: 'ابھی چھوڑیں → لاگ ان پر جائیں' },
  evResendFailed: { en: 'Failed to resend code.', ur: 'کوڈ دوبارہ بھیجنا ناکام ہوا۔' },
  evSuccessTitle: { en: 'Email Verified! 🎉', ur: 'ای میل تصدیق ہوگئی! 🎉' },
  evSuccessMsg:   { en: 'Your email address has been verified successfully. Your account is now active and pending admin approval.', ur: 'آپ کی ای میل کامیابی سے تصدیق ہوگئی۔ آپ کا اکاؤنٹ اب فعال ہے اور ایڈمن کی منظوری کے انتظار میں ہے۔' },
  evSuccessInfo:  { en: '🔔 You will be notified once an admin reviews and approves your account. This usually takes 1–2 business days.', ur: '🔔 جب ایڈمن آپ کے اکاؤنٹ کا جائزہ لے کر منظور کرے گا تو آپ کو مطلع کیا جائے گا۔ یہ عام طور پر 1–2 کاروباری دنوں میں ہوتا ہے۔' },
  evGoToLogin:    { en: '→ Go to Login', ur: '← لاگ ان پر جائیں' },
  evDemoTitle:    { en: 'Your Verification Code', ur: 'آپ کا تصدیقی کوڈ' },
  evDemoNote:     { en: 'Copy this code and paste it below. (Shown because email is in demo mode.)', ur: 'یہ کوڈ کاپی کریں اور نیچے پیسٹ کریں۔ (ڈیمو موڈ میں دکھایا گیا ہے۔)' },
  evLoginBlockNote: { en: '🔒 You must verify your email before you can log in. A fresh code has been sent to your email address.', ur: '🔒 لاگ ان سے پہلے آپ کو اپنی ای میل تصدیق کرنی ہوگی۔ آپ کے ای میل پر نیا کوڈ بھیج دیا گیا ہے۔' },

  // See All Bidding (Farmer)
  menuSeeAllBidding:         { en: 'See All Bidding',        ur: 'تمام بولیاں دیکھیں' },
  seeAllBiddingTitle:        { en: 'See All Bidding',        ur: 'تمام بولیاں دیکھیں' },
  noBiddingActivity:         { en: 'No Bidding Activity',    ur: 'کوئی بولی نہیں' },
  noBiddingSubtitle:         { en: 'When buyers bid on your crops, they will appear here in real time.', ur: 'جب خریدار آپ کی فصلوں پر بولی لگائیں گے تو یہاں نظر آئیں گے۔' },
  biddersCount:              { en: 'Bidders',                ur: 'بولی لگانے والے' },
  winnerLabel:               { en: 'Winner',                 ur: 'فاتح' },
  selectedLabel:             { en: 'Selected',               ur: 'منتخب' },
  cancelOrderQ:              { en: 'Cancel Order?',           ur: 'آرڈر منسوخ کریں؟' },
  cancelOrderConfirmMsg:     { en: "Are you sure you want to cancel this buyer's order? You will need to select another buyer.", ur: 'کیا آپ واقعی اس خریدار کا آرڈر منسوخ کرنا چاہتے ہیں؟ آپ کو دوسرے خریدار کو منتخب کرنا ہوگا۔' },
  selectBuyerQ:              { en: 'Select This Buyer?',      ur: 'خریدار منتخب کریں؟' },
  selectBuyerBtn:            { en: 'Yes, Select',             ur: 'ہاں، منتخب کریں' },
  buyerSelectedBanner:       { en: '✅ Buyer selected. Awaiting payment confirmation.', ur: '✅ خریدار منتخب ہوگیا۔ ادائیگی کا انتظار ہے۔' },
  orderCancelledSelectNew:   { en: 'Order cancelled. Now select another buyer.',       ur: 'آرڈر منسوخ ہوگیا۔ اب دوسرے خریدار کو منتخب کریں۔' },
  farmerSelectAnotherBuyer:  { en: 'The buyer did not make the payment. Please select another buyer from "See All Bidding".', ur: 'خریدار نے ادائیگی نہیں کی۔ براہ کرم "تمام بولیاں دیکھیں" سے دوسرا خریدار منتخب کریں۔' },
  adminCancelSelectNew:      { en: 'The buyer did not send the payment. Please select another buyer from "See All Bidding".', ur: 'خریدار نے ادائیگی نہیں بھیجی۔ براہ کرم "تمام بولیاں دیکھیں" سے دوسرا خریدار منتخب کریں۔' },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => setLanguage(prev => (prev === 'en' ? 'ur' : 'en'));

  const t = (key: string): string => translations[key]?.[language] ?? key;

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t, isUrdu: language === 'ur' }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
